# Generated by Django 4.2.5 on 2024-02-13 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visa',
            field=models.IntegerField(blank=True, choices=[(0, 'Не получилось определить'), (1, 'В наличии'), (2, 'Отсутствует')], null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 13, 17, 37, 249156, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
